//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_FRAMEWORK_4._7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVentas
    {
        public int IdDetalleVenta { get; set; }
        public int IdVenta { get; set; }
        public int IdProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
