//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_FRAMEWORK_4._7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public Ventas()
        {
            this.DetalleVentas = new HashSet<DetalleVentas>();
        }
    
        public int IdVenta { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public decimal Total { get; set; }
        public string Cliente { get; set; }
    
        public virtual ICollection<DetalleVentas> DetalleVentas { get; set; }
    }
}
